using System;
using System.Collections.Generic;

namespace ProjectEuler {

    class PE029 : PESolution {

        void PESolution.printProblemNumber() {
            Console.WriteLine("Problem 29:");
        }

        void PESolution.printProblemStatement() {
            Console.WriteLine("How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?");
        }

        void PESolution.solve() {
            HashSet<double> terms = new HashSet<double>();
            int boundUpper = 100;
            // Brute Force
            for (int a = 2; a <= boundUpper; a++) {
                for (int b = 2; b <= boundUpper; b++) {
                    double term = Math.Pow(a, b);
                    if (!terms.Contains(term)) {
                        terms.Add(term);
                    }
                }
            }
            int answer = terms.Count;

            Console.WriteLine("Answer is {0}", answer);
        }

    }

}
